name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    strategy:
      fail-fast: true
      matrix:
        platform: ['macos-latest', 'ubuntu-latest']
        version: ['v0.1.2']
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install git-metrics
        uses: jdrouet/action-install-git-metrics@main
        with:
          version: ${{ matrix.version }}

      - name: set git config
        shell: bash
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email "$GITHUB_ACTOR_ID+$GITHUB_ACTOR@users.noreply.github.com"

      - name: executing script
        id: test-action
        uses: ./
        with:
          script: |
            pull
            add name 12.3
            show

      - name: Print Output
        run: echo "${{ steps.test-action.outputs.result }}"

  test-continue-on-error:
    name: The script should keep going
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdrouet/action-install-git-metrics@main

      - name: set git config
        shell: bash
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email "$GITHUB_ACTOR_ID+$GITHUB_ACTOR@users.noreply.github.com"

      - uses: ./
        with:
          script: |
            show
            unknown
            show
          continueOnError: true
